batch_size: 16
data_dir_tag: cdfg-control-data-call
epochs: 400
input_data: ./data/cdfgs_control-data-call_20000samples_150x150.npz
learning_rate: 0.01
n_classes: 4
n_features: 200
n_nodes: 300
samples: 20000
test_size: 0.1
validation_size: 0.1
