batch_size: 16
data_dir_tag: cfg
epochs: 400
input_data: ./data/cfgs_20000samples_150x150.npz
learning_rate: 0.01
n_classes: 4
n_features: 67
n_nodes: 150
samples: 20000
test_size: 0.1
validation_size: 0.1
